-- CreateTable
CREATE TABLE `user` (
    `USER_INDEX` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_DISPLAY` VARCHAR(16) NOT NULL,
    `USER_EMAIL` VARCHAR(255) NOT NULL,
    `USER_PASSWORD` VARCHAR(255) NOT NULL,
    `USER_RESTRICTED` BOOLEAN NOT NULL DEFAULT false,
    `USER_PAINTED` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`USER_INDEX`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
