-- CreateTable
CREATE TABLE `pixel` (
    `PIXEL_INDEX` INTEGER NOT NULL AUTO_INCREMENT,
    `PIXEL_POS_X` INTEGER NOT NULL,
    `PIXEL_POS_Y` INTEGER NOT NULL,
    `PIXEL_COLOR_R` INTEGER NOT NULL,
    `PIXEL_COLOR_G` INTEGER NOT NULL,
    `PIXEL_COLOR_B` INTEGER NOT NULL,
    `PIXEL_UUID` VARCHAR(36) NOT NULL,

    UNIQUE INDEX `unique_pixel`(`PIXEL_POS_X`, `PIXEL_POS_Y`),
    PRIMARY KEY (`PIXEL_INDEX`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
